export const OPEN_ADD_REMINDER_CARD = "OPEN_ADD_REMINDER_CARD"
export const CLOSE_ADD_REMINDER_CARD = "CLOSE_ADD_REMINDER_CARD"

export const OPEN_REMINDER_MODAL = "OPEN_REMINDER_MODAL"
export const CLOSE_REMINDER_MODAL = "CLOSE_REMINDER_MODAL"